baseURL = 'https://szxzip.org/'
languageCode = 'en-us'
title = 'Pizxzs'
theme = 'PaperMod'
timeZone = "Asia/Shanghai"

[params]
  defaultTheme = 'auto'

[params.homeInfoParams]
  Title = "Time, forward."
  Content = "时代，前进 | Temps, en avant | Время, вперёд"

[params.fuseOpts]
  isCaseSensitive = 'false'
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ['title', 'permalink', 'summary', 'content']

[params.cover]
  responsiveImages = 'false'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[[menu.main]]
name       = "Search"
identifier = "search"
url        = "/search/"
weight     = 1

[[menu.main]]
name       = "Archives"
identifier = "archives"
url        = "/archives/"
weight     = 2
